### ISSUE TITLE
Call to undefined method getBezeichnungDesTanMediums() 

### ISSUE THREAD

**Issue by MartinWeidner** [nemiah/phpFinTS#152]
Hi,
ich kann mich nicht mit der comdirect verbinden:

```
$fints = new FinTs(
    FHP_BANK_URL,
    FHP_BANK_CODE,
    FHP_ONLINE_BANKING_USERNAME,
    FHP_ONLINE_BANKING_PIN,
    FHP_PRODUCT_NAME,
    FHP_PRODUCT_VERSION
);

$fints->login(902);
```

Fehlermeldung:

> Fatal error: Uncaught Error: Call to undefined method Fhp\Segment\TAN\HITANv6::getBezeichnungDesTanMediums() in /var/www/finTs/vendor/nemiah/php-fints/lib/Fhp/Response/GetTANRequest.php:74 
Stack trace: 
#0 /var/www/finTs/vendor/nemiah/php-fints/lib/Fhp/Dialog/Exception/TANRequiredException.php(37): Fhp\Response\GetTANRequest->getTanMediumName() 
#1 /var/www/finTs/vendor/nemiah/php-fints/lib/Fhp/Dialog/Dialog.php(205): Fhp\Dialog\Exception\TANRequiredException->__construct(Object(Fhp\Response\GetTANRequest), Object(Fhp\Message\Message), Object(Fhp\Dialog\Dialog)) 
#2 /var/www/finTs/vendor/nemiah/php-fints/lib/Fhp/Dialog/Dialog.php(437): Fhp\Dialog\Dialog->sendMessage(Object(Fhp\Message\Message), 902, NULL) 
#3 /var/www/finTs/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(715): Fhp\Dialog\Dialog->initDialog(902, NULL, NULL) 
#4 /var/www/finTs/index.php(114): Fhp\FinTs->login(902) in /var/www/finTs/vendor/nemiah/php-fints/lib/Fhp/Response/GetTANRequest.php on line 74

**Comment by ampaze** [comment]
Danke für den Hinweis, die Methode ist gerade erst mit #141 gerade umbenannt worden. 

@Philipp91 Ich würde sie zusätzlich zu `getTanMediumName` wieder anfügen?
Oder soll man direkt `->bezeichnungDesTanMediums` benutzen?

Ich finde man sollte die Benamung nach Spec zumindest zusätzlich beibehalten. Oder?

**Comment by Philipp91** [comment]
Können wir machen.
Ich habe die Funktion auf Englisch benannt, weil bisher alles im Namespace
Model auf Englisch ist. Man könnte die Tatsache, dass das Protokoll auf
Deutsch spezifiziert ist, als Implementierungsdetail ansehen.

ampaze <notifications@github.com> schrieb am Mi., 27. Nov. 2019, 12:54:

**Comment by ampaze** [comment]
Fände ich glaube nicht schlecht, weil doch einiges eher holprig ins Englische zu übertragen geht. Hab jetzt erstmal die Interface Methode benutzt.

**Comment by MartinWeidner** [comment]
Ich komme da trotzdem nicht weiter...

Gestern hat Login eine TANRequiredException geworfen... Darin enthalten war die PhotoTan Grafik, welche ich angezeigt und gescannt habe.

Die TAN sowie die anderen Parameter (processId, systemId, dialogId, messageNumber) habe ich an submitTanForMechanism() übergeben. getSEPAAccounts lieferte trotzdem eine TANRequiredException. Seit heute morgen bekomme ich aber keine Exception mehr beim Login, sondern ein Response-Objekt mit "Starke Kundenauthentifizierung nicht notwendig". Scheint so, als hätte die comdirect meine TAN geschluckt, aber getSEPAAccounts liefert immer noch die Exception... Muss ich da zwischendurch etwas anderes aufrufen?

**Comment by ampaze** [comment]
Jetzt wird es interessant.

Gedacht war es so, dass nach Übermittlung einer TAN eben genau der Fall eintritt **Starke Kundenauthentifizierung nicht notwendig** und dann auch für die Abfrage der Konten nicht mehr nötig ist. 

Das scheint bei der Comdirect jetzt nicht der Fall zu sein.

Also du machst
```
->login
->getSEPAAccounts
```

?

Die Möglichkeit die Antwort nach der TAN-Übermittlung (mit zwischenzeitlicher Unterbrechung) zu verwerten ist momentan noch nicht vorhanden.

**Comment by MartinWeidner** [comment]
> Also du machst
> ->login
> ->getSEPAAccounts
> ?

Ja genau. Hier mal der Log (Username und PIN mit XXX entfernt)

```
New Dialog constructed

SYNC initialize
> HNHBK:1:3+000000000363+300+0+1'HNVSK:998:3+PIN:1+998+1+1::0+1:20191128:130932+2:2:13:@8@00000000:5:1+280:20041144:xxxxxxxxx:V:0:0+0'HNVSD:999:1+@202@HNSHK:2:4+PIN:1+999+7414494+1+1+1::0+1+1:20191128:130932+1:999:1+6:10:16+280:20041144:xxxxxxxxx:S:0:0'HKIDN:3:2+280:20041144+xxxxxxxxx+0+1'HKVVB:4:3+0+0+0+ownCRM+1.0'HKSYN:5:3+0'HNSHA:6:2+7414494++xxxxxx''HNHBS:7:1+1'
< HNHBK:1:3+000000002165+300+96xNAQDNsW4BAAAObddUEAQFCgQA+1+96xNAQDNsW4BAAAObddUEAQFCgQA:1'HNVSK:998:3+PIN:1+998+1+2::0+1:20191128:130932+2:2:13:@8@00000000:5:1+280:20041144:xxxxxxxxx:V:0:0+0'HNVSD:999:1+@1944@HNSHK:2:4+PIN:1+999+7414494+1+1+2::0+1+1:20191128:130932+1:999:1+6:10:16+280:20041144:xxxxxxxxx:S:0:0'HIRMG:3:2+3060::Bitte beachten Sie die enthaltenen Warnungen/Hinweise.'HIRMS:4:2:5+0020::Auftrag ausgefuehrt.'HIRMS:5:2:4+3050::BPD nicht mehr aktuell, aktuelle Version enthalten.+0020::Dialog initialisiert.+3920::Verf�gbare TAN-Verfahren?: photoTAN und mobileTAN.:902:901'HIBPA:6:3:4+6+280:20041144+comdirect bank+10+1+300+200'HIKOM:7:4:4+280:20041144+1+3:https?://fints.comdirect.de/fints'HISHV:8:3:4+J+PIN:1'HIFGBS:9:3:4+999+1'HIFRDS:10:1:4+999+1'HIKAZS:11:5:4+999+1+540:J:N'HISALS:12:5:4+999+1'HIWPDS:13:5:4+999+1+J:J:J'DIKKSS:14:3:4+999+1+0'DIKKUS:15:2:4+999+1+0+9999:J:J'DIKAUS:16:2:4+999+1+0+J'HISPAS:17:1:4+999+0+0+N:N:N:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03.xsd'HICCSS:18:1:4+999+1+0'HICCMS:19:1:4+999+1+0+20:N:N'HICSES:20:1:4+999+1+0+1:365'HICSAS:21:1:4+999+1+0+1:365'HICSBS:22:1:4+999+1+0+N:N'HICSLS:23:1:4+999+1+0+J'HICDES:24:1:4+999+1+0+10:1:365:0102030612:010203040506070809101112131415161718192021222324252627282930:01:12345'HICDBS:25:1:4+999+1+0+N'HICDNS:26:1:4+999+1+0+0:1:365:J:J:J:J:J:J:J:J:J:0102030612:010203040506070809101112131415161718192021222324252627282930:01:12345'HICDUS:27:1:4+999+1+0+1:1:365:1:N:N'HICDLS:28:1:4+999+1+0+1:1:N:N'HITANS:29:6:4+1+1+1+N:N:0:901:2:TechnicalId901:::mobileTAN-Verfahren:6:1:Freigabe durch mobileTAN:1:N:4:N:0:0:N:N:00:0:N::902:2:MS1.0.0:::photoTAN-Verfahren:6:1:Freigabe durch photoTAN:1:N:4:N:0:0:N:N:00:0:N:'HIPINS:30:1:4+1+1+0+6:6:6:Zugangsnummer:Zugangsnummer:HKSAL:J:HKFGB:N:HKFRD:N:HKKAZ:J:HKWPD:N:HKSPA:N:HKCCM:J:HKCCS:J:HKCSE:J:HKCSA:J:HKCSB:N:HKCSL:J:HKCDE:J:HKCDB:N:HKCDN:J:HKCDU:J:HKCDL:J:DKKKU:J:DKKKS:J:DKKAU:J:HKTAN:N'HISYN:31:4:5+9a5NAQDNsW4BAAAObddUEAQFCgQA'HIKIM:32:2+Sie haben neue Post!+Sie haben neue Mitteilungen erhalten. Bitte rufen Sie die Unterlagen in Ihrer Postbox ab.'HNSHA:33:2+7414494''HNHBS:34:1+1'
[HIRMG] 3060: Bitte beachten Sie die enthaltenen Warnungen/Hinweise.
[HIRMS] 0020: Dialog initialisiert.
[HIRMS] 3050: BPD nicht mehr aktuell, aktuelle Version enthalten.
[HIRMS] 3920: Verfügbare TAN-Verfahren? ( photoTAN und mobileTAN., 902, 901)
Received system id: 9a5NAQDNsW4BAAAObddUEAQFCgQA
Received dialog id: 96xNAQDNsW4BAAAObddUEAQFCgQA
Supported TAN mechanisms: mobileTAN-Verfahren (901), photoTAN-Verfahren (902)
SYNC end

END initialize
> HNHBK:1:3+000000000408+300+96xNAQDNsW4BAAAObddUEAQFCgQA+2'HNVSK:998:3+PIN:1+998+1+1::9a5NAQDNsW4BAAAObddUEAQFCgQA+1:20191128:130932+2:2:13:@8@00000000:5:1+280:20041144:xxxxxxxxx:V:0:0+0'HNVSD:999:1+@193@HNSHK:2:4+PIN:1+999+8754662+1+1+1::9a5NAQDNsW4BAAAObddUEAQFCgQA+1+1:20191128:130932+1:999:1+6:10:16+280:20041144:xxxxxxxxx:S:0:0'HKEND:3:1+96xNAQDNsW4BAAAObddUEAQFCgQA'HNSHA:4:2+8754662++xxxxxx''HNHBS:5:1+2'
< HNHBK:1:3+000000000426+300+96xNAQDNsW4BAAAObddUEAQFCgQA+2+96xNAQDNsW4BAAAObddUEAQFCgQA:2'HNVSK:998:3+PIN:1+998+1+2::9a5NAQDNsW4BAAAObddUEAQFCgQA+1+2:2:13:@8@00000000:5:1+280:20041144:xxxxxxxxx:V:0:0+0'HNVSD:999:1+@196@HNSHK:2:4+PIN:1+999+8754662+1+1+2::9a5NAQDNsW4BAAAObddUEAQFCgQA+1+1+1:999:1+6:10:16+280:20041144:xxxxxxxxx:S:0:0'HIRMG:3:2+0010::Nachricht entgegengenommen.+0100::Dialog beendet.'HNSHA:4:2+8754662''HNHBS:5:1+2'
[HIRMG] 0010: Nachricht entgegengenommen.
[HIRMG] 0100: Dialog beendet.
Resetting dialog ID and message number count
END end

DIALOG initialize
Registered product: ownCRM 1.0
> HNHBK:1:3+000000000455+300+0+1'HNVSK:998:3+PIN:2+998+1+1::9a5NAQDNsW4BAAAObddUEAQFCgQA+1:20191128:130932+2:2:13:@8@00000000:5:1+280:20041144:xxxxxxxxx:V:0:0+0'HNVSD:999:1+@267@HNSHK:2:4+PIN:2+902+5492200+1+1+1::9a5NAQDNsW4BAAAObddUEAQFCgQA+1+1:20191128:130932+1:999:1+6:10:16+280:20041144:xxxxxxxxx:S:0:0'HKIDN:3:2+280:20041144+xxxxxxxxx+9a5NAQDNsW4BAAAObddUEAQFCgQA+1'HKVVB:4:3+0+0+0+ownCRM+1.0'HKTAN:5:6+4+HKIDN++++N'HNSHA:6:2+5492200++xxxxxx''HNHBS:7:1+1'
< HNHBK:1:3+000000002808+300+dLJNAQDNsW4BAAAObddUEAQFCgQA+1+dLJNAQDNsW4BAAAObddUEAQFCgQA:1'HNVSK:998:3+PIN:2+998+1+2::9a5NAQDNsW4BAAAObddUEAQFCgQA+1:20191128:130932+2:2:13:@8@00000000:5:1+280:20041144:xxxxxxxxx:V:0:0+0'HNVSD:999:1+@2560@HNSHK:2:4+PIN:2+902+5492200+1+1+2::9a5NAQDNsW4BAAAObddUEAQFCgQA+1+1:20191128:130932+1:999:1+6:10:16+280:20041144:xxxxxxxxx:S:0:0'HIRMG:3:2+3060::Bitte beachten Sie die enthaltenen Warnungen/Hinweise.'HIRMS:4:2:4+3050::UPD nicht mehr aktuell, aktuelle Version enthalten.+3050::BPD nicht mehr aktuell, aktuelle Version enthalten.+0020::Dialog initialisiert.+3920::Verf�gbare TAN-Verfahren?: photoTAN und mobileTAN.:902:901'HIRMS:5:2:5+3076::Starke Kundenauthentifizierung nicht notwendig.'HIBPA:6:3:4+6+280:20041144+comdirect bank+10+1+300+200'HIKOM:7:4:4+280:20041144+1+3:https?://fints.comdirect.de/fints'HISHV:8:3:4+J+PIN:1'HIFGBS:9:3:4+999+1'HIFRDS:10:1:4+999+1'HIKAZS:11:5:4+999+1+540:J:N'HISALS:12:5:4+999+1'HIWPDS:13:5:4+999+1+J:J:J'DIKKSS:14:3:4+999+1+0'DIKKUS:15:2:4+999+1+0+9999:J:J'DIKAUS:16:2:4+999+1+0+J'HISPAS:17:1:4+999+0+0+N:N:N:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03.xsd'HICCSS:18:1:4+999+1+0'HICCMS:19:1:4+999+1+0+20:N:N'HICSES:20:1:4+999+1+0+1:365'HICSAS:21:1:4+999+1+0+1:365'HICSBS:22:1:4+999+1+0+N:N'HICSLS:23:1:4+999+1+0+J'HICDES:24:1:4+999+1+0+10:1:365:0102030612:010203040506070809101112131415161718192021222324252627282930:01:12345'HICDBS:25:1:4+999+1+0+N'HICDNS:26:1:4+999+1+0+0:1:365:J:J:J:J:J:J:J:J:J:0102030612:010203040506070809101112131415161718192021222324252627282930:01:12345'HICDUS:27:1:4+999+1+0+1:1:365:1:N:N'HICDLS:28:1:4+999+1+0+1:1:N:N'HITANS:29:6:4+1+1+1+N:N:0:901:2:TechnicalId901:::mobileTAN-Verfahren:6:1:Freigabe durch mobileTAN:1:N:4:N:0:0:N:N:00:0:N::902:2:MS1.0.0:::photoTAN-Verfahren:6:1:Freigabe durch photoTAN:1:N:4:N:0:0:N:N:00:0:N:'HIPINS:30:1:4+1+1+0+6:6:6:Zugangsnummer:Zugangsnummer:HKSAL:J:HKFGB:N:HKFRD:N:HKKAZ:J:HKWPD:N:HKSPA:N:HKCCM:J:HKCCS:J:HKCSE:J:HKCSA:J:HKCSB:N:HKCSL:J:HKCDE:J:HKCDB:N:HKCDN:J:HKCDU:J:HKCDL:J:DKKKU:J:DKKKS:J:DKKAU:J:HKTAN:N'HIUPA:31:4:4+xxxxxxxxx+1+0'HIUPD:32:6:4+577684400:Girokonto:280:20041144+DE46200411440577684400+xxxxxxxxx++EUR+Martin Weidner++Girokonto++HKSAK:1+HKISA:1+HKSSP:1+HKSAL:1+HKKAZ:1+HKCDB:1+HKCSL:1+HKCDL:1+HKCDU:1+HKCSA:1+HKCDN:1+HKCSB:1+HKCCM:1+HKCCS:1+HKCDE:1+HKCSE:1+HKTAN:1+HKFRD:1+HKSPA:1'HIUPD:33:6:4+577684405:Tagesgeld PLUS:280:20041144+DE08200411440577684405+xxxxxxxxx++EUR+Martin Weidner++Tagesgeld PLUS++HKSAK:1+HKISA:1+HKSSP:1+HKSAL:1+HKKAZ:1+HKCSL:1+HKCSA:1+HKCSB:1+HKCCS:1+HKCSE:1+HKTAN:1+HKFRD:1+HKSPA:1'HIKIM:34:2+Sie haben neue Post!+Sie haben neue Mitteilungen erhalten. Bitte rufen Sie die Unterlagen in Ihrer Postbox ab.'HITAN:35:6:5+4++noref+nochallenge'HNSHA:36:2+5492200''HNHBS:37:1+1'
[HIRMG] 3060: Bitte beachten Sie die enthaltenen Warnungen/Hinweise.
[HIRMS] 3050: BPD nicht mehr aktuell, aktuelle Version enthalten.
[HIRMS] 0020: Dialog initialisiert.
[HIRMS] 3920: Verfügbare TAN-Verfahren? ( photoTAN und mobileTAN., 902, 901)
[HIRMS] 3076: Starke Kundenauthentifizierung nicht notwendig.
Received dialog ID: dLJNAQDNsW4BAAAObddUEAQFCgQA
DIALOG end
Fhp\FinTs:getSEPAAccounts called

HKSPA (SEPA accounts) initialize
> HNHBK:1:3+000000000380+300+dLJNAQDNsW4BAAAObddUEAQFCgQA+2'HNVSK:998:3+PIN:2+998+1+1::9a5NAQDNsW4BAAAObddUEAQFCgQA+1:20191128:130932+2:2:13:@8@00000000:5:1+280:20041144:xxxxxxxxx:V:0:0+0'HNVSD:999:1+@165@HNSHK:2:4+PIN:2+902+7667168+1+1+1::9a5NAQDNsW4BAAAObddUEAQFCgQA+1+1:20191128:130932+1:999:1+6:10:16+280:20041144:xxxxxxxxx:S:0:0'HKSPA:3:1+'HNSHA:4:2+7667168++xxxxxx''HNHBS:5:1+2'
< HNHBK:1:3+000000000637+300+dLJNAQDNsW4BAAAObddUEAQFCgQA+2+dLJNAQDNsW4BAAAObddUEAQFCgQA:2'HNVSK:998:3+PIN:2+998+1+2::9a5NAQDNsW4BAAAObddUEAQFCgQA+1:20191128:130932+2:2:13:@8@00000000:5:1+280:20041144:xxxxxxxxx:V:0:0+0'HNVSD:999:1+@391@HNSHK:2:4+PIN:2+902+7667168+1+1+2::9a5NAQDNsW4BAAAObddUEAQFCgQA+1+1:20191128:130932+1:999:1+6:10:16+280:20041144:xxxxxxxxx:S:0:0'HIRMG:3:2+0010::Nachricht entgegengenommen.'HIRMS:4:2:3+0010::Auftrag entgegengenommen.'HISPA:5:1:3+J:DE46200411440577684400:COBADEHD044:577684400:Girokonto:280:20041144+J:DE08200411440577684405:COBADEHD044:577684405:Tagesgeld PLUS:280:20041144'HNSHA:6:2+7667168''HNHBS:7:1+2'
[HIRMG] 0010: Nachricht entgegengenommen.
[HIRMS] 0010: Auftrag entgegengenommen.
```

**Comment by ampaze** [comment]
Interessant. Es kommt nämlich gar keine TAN-Nachfrage von der Bank 😁 

Aber 
> 0010: Auftrag entgegengenommen.

wird nicht als fehlerfreie Ausführung erkannt. Ich gucke mal in der Spezifikation nach.

**Comment by ampaze** [comment]
@Philipp91 

Du bist gut im Protokoll drin. Wäre es nicht sinnvoll die `isStrongAuthRequired`-Methode zu ersetzen durch 
```php
return $this->getSegment('HITAN') != null;
```

**Comment by MartinWeidner** [comment]
Nach `composer update` kommt jetzt bei getSEPAAccounts diese Meldung:

> Fatal error: Uncaught Error: Call to a member function getTanMediumName() on null in /var/www/vendor/nemiah/php-fints/lib/Fhp/Response/GetTANRequest.php:74 Stack trace: #0 /var/www/vendor/nemiah/php-fints/lib/Fhp/Dialog/Exception/TANRequiredException.php(37): Fhp\Response\GetTANRequest->getTanMediumName() #1 /var/www/vendor/nemiah/php-fints/lib/Fhp/Dialog/Dialog.php(205): Fhp\Dialog\Exception\TANRequiredException->__construct(Object(Fhp\Response\GetTANRequest), Object(Fhp\Message\Message), Object(Fhp\Dialog\Dialog)) #2 /var/www/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(159): Fhp\Dialog\Dialog->sendMessage(Object(Fhp\Message\Message), NULL, NULL) #3 /var/www/index.php(156): Fhp\FinTs->getSEPAAccounts() #4 {main} thrown in /var/www/vendor/nemiah/php-fints/lib/Fhp/Response/GetTANRequest.php on line 74

**Comment by ampaze** [comment]
Ja, das liegt an dem Fehler in `isStrongAuthRequired`.
Noch etwas Geduld :)

**Comment by ampaze** [comment]
@MartinWeidner Probier es doch jetzt nochmal mit dem master e7ce2cd4e9da4c9ab5165e997fcdae3129702fd5 bitte.

**Comment by MartinWeidner** [comment]
Funktioniert!! Danke für die Unterstützung!
