### ISSUE TITLE
Norisbank - PhotoTAN Unterstützung?

### ISSUE THREAD

**Issue by CreativDesigner** [nemiah/phpFinTS#215]
Hey zusammen,

ich sitze gerade dabei mein Konto bei der Norisbank anzubinden. Diese fordern genau wie die deutsche Bank das Verfahren über PhotoTAN direkt beim Login. Hat das schon jemand ans laufen gebracht oder könnte mir ansatzweise dazu was sagen?

Ich bin jetzt schon den ganzen Tag dabei und blicke nun überhaupt nicht mehr durch. Ein Login ist logischerweise nicht möglich und endet in der TANRequiredException. Als tanMechanism erhalte ich 902 PhotoTAN und ein Aufruf der TANDevices bleibt Ergebnislos.

Ich habe mich leider noch nicht genauer mit dem Thema HBCI und jetzt FinTS beschäftigt um den genauen Ablauf zu verstehen. Aber vielleicht ist das mit der PhotoTAN ja bisher auch noch nicht möglich, habe in der Suche einige erst vor kurzem geschriebenen Beiträge dazu gesehen.

**Comment by ampaze** [comment]
Tan Devices braucht man nicht bei jeder Bank. Wenn du eine TANRequiredException bekommst, dann funktioniert alles. 

Guck dir dazu `TANRequiredException::getResponse` und  `GetTANRequest::getTanChallengeImage` an.

----

Wenn du neu implementierst, würde ich dir empfehlen FinTsNew zu verwenden.

**Comment by NabilHanna** [comment]
Ich benutze mittlerweile die FinTsNew und bekomme bei der Norisbank folgendes:
```
Uncaught Fhp\Protocol\UnexpectedResponseException: Unexpected TAN request in /www/htdocs/.../vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php:309
Stack trace:
#0 /www/htdocs/.../vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php(723): Fhp\FinTsNew->execute(Object(Fhp\Protocol\DialogInitialization))
#1 /www/htdocs/.../vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php(572): Fhp\FinTsNew->executeWeakDialogInitialization(NULL)
#2 /www/htdocs/.../vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php(246): Fhp\FinTsNew->ensureSynchronized()
#3 /www/htdocs/.../ajax/bank.php(257): Fhp\FinTsNew->login()
#4 {main}
  thrown in <b>/www/htdocs/.../vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php</b> on line <b>309</b><br>
```

```
[D] < HNHBK:1:3+000000003794+300+wO95oYe9phIy20200311211348140%+1+wO95oYe9phIy20200311211348140%:1'HNVSK:998:3+PIN:1+998+1+2::3761410428726000VV9RCMXBG5NDPO+1:20200311:211348+2:2:13:@8@        :5:1+280:10077777:<PRIVATE_>:V:0:0+0'HNVSD:999:1+@3539@HIRMG:2:2+0020::Dialoginitialisierung erfolgreich.+3060::Teilweise liegen Warnungen/Hinweise vor.'HIRMS:3:2:3+0020::Information fehlerfrei entgegengenommen.'HIRMS:4:2:4+3920::Meldung unterstützter Ein- und Zwei-Schritt-Verfahren:902+0010::Auftrag entgegengenommen. Freigabe durch TAN erforderlich.'HIRMS:5:2:5+0030::Auftrag empfangen - Sicherheitsfreigabe erforderlich'HIRMS:6:2:6+0020::Auftrag ausgeführt.'HISYN:7:4:6+3761410428726000VV9RCMXBG5NDPO'HITAN:8:6:5+4++qYvTDMUH20200311211348504#LPE#+Bitte geben Sie die photoTan ein+@3003@ 	image/png®‰PNG

   
IHDR   Ò   Ò   °û	  uIDATxÚí¡r[IEôþ0ƒ€ sCB€?ÁÀ0`h`¨}µªÚª­§dÛgo?K£s+(%ÞŒºÚ}u{n¯¶B,Ž•G ;aØ	aØ	ÃNÃNvBvÂ°Â°†0ìöáùùùæææêêêÃ‡+!V«ËËË/_¾üüù³+ìÖëµ-æ¸¸¸¸¿¿Ï‡Ýs®ø3ê‘·*þmÝl6«øÏœ÷ë×¯XØMõœg**¸¾¾Ž…ÝÄ!<PQd±°;;;ó@E±°ó(…a';!;aØ	Ã®9ì&¶{{{ûòò¢Î=^__ïîîÎÏÏ.ì¦˜óëSä\Ø™çN!ç\Øù­œDŸœa';ÃÎ°>ì¾ßn6Ócm×ëíÓÓþ—l¿o¶›ÕvµÞ®Ÿ¶OÅu
—^³gåÙó”ž°°¯ùó”žíë´Ãnw<»Ó!í}ÉßßÍîßô
×),\zÍž•gÏSzÂÂ¾æÏSzB´¯Ó»Žg÷oÿÆþõ¢â:……K¯Ù³òìyJOXØ×üyJOˆöe¶3Û™í–¯í¦ƒÙÏããïj é[Ù}7ÛÇâ:……K¯Ù³òìyJOXØ×üyJOˆö%“2ÙÚ‡A8gjˆÍU¸$ã€1¢ÈNc¾0bèÃ†¬Šæµªo*Õ«Šb¥;ùÂ¨f6ì œ35Äæ*\’qÀQd§1_1t³ÙÎl­íœ35Äæ*\’qÀQd§1_1tÅ1!“]6ì˜vÉ^ÃTÑFÎŽtd¦ÿ2n;lØ±_óÙk˜NÐXÅ"e…)"¬Ú6ì˜vÉ^ÃTÑFÎŽtd¦ÿRbm¶3Û™í‚µÐ.Ùk˜*ÚÈÙ‘ŽÌô_Æme²B&»÷ÃPp‰sUV®¨´©•+QG¶ø„ƒ„êŠ+U!••+ºEjåJÕˆŠ)¶ø„ƒ„ê.q®ÊÊ•6µr…##êÈvŸÐlg¶3ÛýÚîí=À%ÎUY¹¢Ò¦V®pdDÙ.àÊd…L¶‘ÉBžØÇm+Ì:¤S²]ø5 íô„j;X9õU{•Z3¤šÐò³P£ž“…<±ÛV˜uH#¦d»ðk Ú©ÙÎlg¶ëd²'öqÛ
³iÄ”l~
@;•É
™,ý°Xk¥õÜB³$ææÔvO6u+¶Âm ìb]_•¾4Ô…íC˜¿IÛÍ±Ô=±Jµwaëq­tá¢ž[h–ÄÜœÚîÉ¦nÅ–ºÙÎlg¶[ÅôÖã+)ž¡w±çIi²¥¯¡[±n+“2YÊdá»*¼1>è]ÜçRò%fÚ÷°µ|W¥’C5tóìóm	9u25hX&ßUá­ˆñAïâ>—ª/1Ó¾Ívf;³]ŽÉÂwUx+b|Ð»¸Ï¥*äKÌ´o™¬É³ëq­(žl
Km›ŒÓvCŸ>lw1ìúªh lJÝÖ6+"¦v„>}Ø~;ØãZQ<Ù:–Ú6'¦í†>}Øîb³Ùî}j;ÒãZQ<Ù:–Ú6'¦í†>Ýîb!“íÔd›Ké‰)§bxß¶¢ä¦Ôg¤t«É²ú&õ{Ê»Þ@«h)=i?Ãj²ŒÍÅôÄS1¼o[QrSê3Rº‡ÕdÍvf»wÐd›Ké‰)§bxß¶¢ä¦Ôg¤t«É
™lkw1c²¡{²ì6kì]!µ·ä…úŸ©í˜&QªÒBÓ˜ç|WHÿ(9Â ŽÀA˜,S`Kœ44›†9,Áw…ÔÞ’ÿê6Û™íÌvÁîbÆdC÷dÙmÖØ»BjoÉÿ
õ?Ëd…L–z3–ê°¹³9°ì|XguJZ>Ê°KÍ¹õœÅ|9ÙdDv>¬×0%¶eØ±{©!n›šD“bßð|XguJZ6Û™íÌvÐ»˜±°T‡mÌ…˜ÍeçÃ:«SÒ²LVÈdcaçà0_&¤6î‹ÍêóI>°ƒ“!˜S	R÷Å¦kô9‡žNØÁ98Ì—	i ûb³„ú|’Ívf;³]omGæà0_&¤6î‹ÍêóI>°2Ùð‡¥|€cwiCók922/^’û¥Jé5lÂûžÝÂê«‘ç’ÕðQ:>•^Ãæé0É‘Ý9íãÈÈ¼xIîo¶3Û™íjŽO¥×°y:LrdwNû822/^’ûËd…L6vL©d½²ð³oMÝ]eû2ìÞúû>,L*¿ø³Ïb•\ê6Û—a÷V5Ò°R¯,ú,Æ[SwWÙ¾;³Ùîk; T²^YøYŒ·¦î®²}vB&»¬w1¢X)…1æoòfë°ù>lÞîqª¡>°Ôoî1ÇÏ'[‡M¼`(S“
u½¦Æ˜¿qÈs˜­Ãæû°y»f;³Ù{#Š•RcþÆ!Ïa¶›ïÃæíÊd…L–~XjžlŒ·2Vˆ8{ÌÍ©ÍíyïbXo-9©‚ÕI¨Šù›´ùŸâæ	Ùå’sy+Dœ=ææÔæö<ˆw±ÙÎlw(µ]džlŒ·2Vˆ8{ÌÍ©ÍíYïb!“
Nái› SRNSnÆ¤‘™v‡n
3í{•¢o¦BIKHù{’Ö>ÚKºGÇÔ A4Ù¾	2%å4åfL™içpèÖ0Ó¾Ívf;³žÂÓ6A¦¤œ¦ÜŒI#3íÝfÚ·LVÈdƒÝÅÞK…*mÛ
\D[¡¿SÊj”~»ojAÝ¢íN*ä ãIÊ'e”îâï¥B•¶í.¢­Ðß)ç
e¶3Û™í˜¸ä½T¨Ò¶ÝÀE´ú;¥\¡d²B&K5YÈTN÷RWSÜv°ƒ“X[›–Ð¸¯Þªö	;8w†uó¶)§û
©«)nk¶3Û™í:5YÈTN÷RWSÜv°2Ù
»ÔLÕ¾y:l~kJ'eíkÇ§R]š2Ø7a‚M4L)¬heûÄ¥¶rf¦jß<6¿5¥“2ŠÎö5ˆã“ÙÎlw¸µ]d¦jß<6¿5¥“2ŠÎö¥ã“É¾÷=YÖ›Riag:ihºnŸÿÕ	Ýca)ÝÖ¬L9Í›ìs„9¡{²¬6¥ÒÂ?FL'
M×íó¿2Û™íÌv÷dYlJ¥ÅµÑICÓuûü¯d²B&û›éÙ™{ !Æ—úØb©©'÷žlêfT¨JýìŠÕm©'÷žlêhˆñ¥þ‡öåfXjê	Ç½'k¶3Û½Km—¹b|©ÿ=À!–šzBïÉ
™lkØ!¯$æžou;3>žr|J¹KvÈ=„ù‰@u!ÔÿÇ*Ô”JÊoe”°C^IÌ=‰þÉt;3>žr|J¹K™íÌvf»ÿSÛ½Ý+‰¹'áÚ.ÒíÌøxÊñ)å.%“2ÙÎ{²¬ß‘æÆ‰6)
2Ð¶FêaoŽ±<TF6ÎxH©°&kk-öž,ë7F¤¹q¢MNE´Ï#Úlg¶3ÛÅîÉ²~cDš'Ú¤4PÈ@Û©e²B&[ë..qÉ/ë›øâÈprs|b“ƒŽ1ìRss#
C30BU#œ¥Á<PØ,c»ÔÔ×Ü ×›Ëpd89ˆ9>±ÉAf;³Ùv—¸dŠ—õMü	qd89ˆ9>±ÉA2Y!“5ì;ÃNvÂ°[.ì^^^üVÆÆëëëÁ…Ýíí­_ÌØ¸»»;¸°;;;›"Ïœ7jž›bîüüüàÂNÃNvÂ°3ì„a'»ß`b©ž¦X:ì®®®<MQÁååe,ìnnn<PQÁõõu,ìžŸŸ×ëµg*þŒ‹‹‹?~ÄÂnÂÃÃƒÇ*þŒûûûjKA]!™"ïãÇ®Ø›ç¾}ûö†N–7isÓ_Û¯_¿~þüYn+vøôéÓTÏÿ¶Â°"Ó·çÃNvBvÂ°Â°††0ì„0ì„a'NF2ñHäO    IEND®B`‚''HNHBS:9:1+1'

```

**Comment by ampaze** [comment]
Das dürfte dasselbe Problem sein wie #229 , dort ist ein Workaround beschrieben, den du mal probieren kannst. https://github.com/nemiah/phpFinTS/issues/229#issuecomment-584406277 bzw. https://github.com/nemiah/phpFinTS/issues/238#issuecomment-587098087

Da @Philipp91 untergetaucht scheint, ist die Arbeite an der Sache leider etwas eingeschlafen.

**Comment by Philipp91** [comment]
Habe den Thread schon gesehen. Bin nicht wirklich untergetaucht, war nur mit privatem Umzug beschäftigt und habe in den anderen Threads nichts gesehen, wo ich wirklich helfen konnte. Aber das hier schaue ich mir nachher oder am Wochenende an.

**Comment by Philipp91** [comment]
@NabilHanna Welche Aufrufe hast du vor `login()` schon gemacht (also in derselben PHP-Sitzung)? Funktioniert es, wenn du vorher `getTanModes()` aufrufst (wie [hier](https://github.com/nemiah/phpFinTS/issues/229#issuecomment-581060890) genauer beschrieben), auch wenn du dessen Rückgabewert einfach ignorierst? Und könntest du bitte die Anfragenachricht an die Bank posten, auf die du die oben gepostete Antwortnachricht bekommst?

**Comment by NabilHanna** [comment]
Vor login() hatte ich selectTanMode(). TanMode hole ich aus der Datenbank, da bereits vom User gesetzt bei der Einrichtung.

Wenn ich nun getTanModes() aufrufe wie beschrieben, dann funktioniert die Norisbank auch. Klasse, und danke für den Tip.

Anbei noch die Anfragenachricht von vorhin:
```
[D] > HNHBK:1:3+000000000145+300+0+1'HKIDN:2:2+280:10077777+9999999999+0+0'HKVVB:3:3+0+0+0+<PRIVATE________________>+1.0'HKTAN:4:6+4+HKIDN'HNHBS:5:1+1'
[D] < HNHBK:1:3+000000004545+300+7QHoLC57P#kJ20200311211347777%+1+7QHoLC57P#kJ20200311211347777%:1'HIRMG:2:2+0020::Dialoginitialisierung erfolgreich.+0010::Nachricht entgegengenommen.'HIRMS:3:2:2+0020::Information fehlerfrei entgegengenommen.'HIRMS:4:2:3+1040::BPD nicht mehr aktuell. Aktuelle Version folgt.+1050::UPD nicht mehr aktuell. Aktuelle Version folgt.'HIBPA:5:3:3+35+280:10077777+norisbank+0+1+300+0'HIKOM:6:4:3+280:10077777+1+3:https?://fints.norisbank.de::UUE:1'HIKPV:7:1:3+6:1'HITANS:8:4:3+1+1+1+N:N:1:901:2:MTAN:::Mobile-TAN:6:1:mobileTAN:256:1:J:1:0:N:N:N:N:N:00:0:1:902:2:MS1.0.0:::photoTAN-Verfahren:7:1:Freigabe durch photoTAN:1::J:1:0:N:N:N:N:N:00:0'HITANS:9:5:3+1+1+1+N:N:1:901:2:MTAN:::Mobile-TAN:6:1:mobileTAN:256:1:J:1:0:N:0:0:N:N:00:0:1:902:2:MS1.0.0:::photoTAN-Verfahren:7:1:Freigabe durch photoTAN:1::J:1:0:N:0:0:N:N:00:0'HITANS:10:6:3+1+1+1+N:N:1:901:2:MTAN:::Mobile-TAN:6:1:mobileTAN:256:J:1:N:0:0:N:N:00:0:N:1:902:2:MS1.0.0:::photoTAN-Verfahren:7:1:Freigabe durch photoTAN:1:J:1:N:0:0:N:N:00:0:N'HIPINS:11:1:3+1+1+1+5:5:6:Benutzerkennung:Kundenkennung:HKBBS:N:HKDMB:N:HKDML:J:HKCDB:N:HKBSL:J:HKDSC:J:HKDSL:J:HKCSB:N:HKCDL:J:HKCMB:N:HKBSA:J:HKUMB:J:HKCSE:J:HKCML:J:HKDME:J:HKBMB:N:HKSPA:N:HKDBS:N:HKKAZ:J:HKPRO:N:HKBME:J:HKCSA:J:HKSAL:N:HKCCM:J:HKDMC:J:HKCDE:J:HKWPD:N:HKTAN:N:DKPSP:J:HKDSA:J:HKBSE:J:HKDSE:J:HKPSP:J:HKCME:J:HKBML:J:HKAUB:J:HKCCS:J:HKCSL:J:HKCDN:J:HKFRD:N'DIPINS:12:1:3+1+1+HKBBS:N:HKDMB:N:HKDML:J:HKCDB:N:HKBSL:J:HKDSC:J:HKDSL:J:HKCSB:N:HKCDL:J:HKCMB:N:HKBSA:J:HKUMB:J:HKCSE:J:HKCML:J:HKDME:J:HKBMB:N:HKSPA:N:HKDBS:N:HKKAZ:J:HKPRO:N:HKBME:J:HKCSA:J:HKSAL:N:HKCCM:J:HKDMC:J:HKCDE:J:HKWPD:N:HKTAN:N:DKPSP:J:HKDSA:J:HKBSE:J:HKDSE:J:HKCME:J:HKBML:J:HKAUB:J:HKCCS:J:HKCSL:J:HKCDN:J:HKFRD:N'HIPSPS:13:1:3+1+1+1'DIPSPS:14:1:3+1+1'HIPROS:15:2:3+1+1'HIPROS:16:3:3+1+1'HIPROS:17:4:3+1+1+1'HIFRDS:18:1:3+1+1'HIKAZS:19:4:3+1+1+90:N'HIKAZS:20:5:3+1+1+90:N:N'HIKAZS:21:6:3+1+1+1+90:N:N'HIKAZS:22:7:3+1+1+1+90:N:N'HISALS:23:3:3+1+1'HISALS:24:4:3+1+1'HISALS:25:5:3+1+1'HISALS:26:6:3+1+1+1'HISALS:27:7:3+1+1+1'HIWPDS:28:2:3+1+1+N'HIWPDS:29:3:3+1+1+N'HIWPDS:30:4:3+1+1+N:N:N'HIWPDS:31:5:3+1+1+N:N:N'HIWPDS:32:6:3+1+1+1+N:N:N'HIUMBS:33:1:3+1+1+4:51:53:54:56:67:69'HIUMBS:34:2:3+1+1+1+4:51:53:54:56:67:69'HIAUBS:35:3:3+1+1+1'HIAUBS:36:4:3+1+1+1'HIAUBS:37:5:3+1+1+1'HIAUBS:38:6:3+1+1+1+1'HISPAS:39:1:3+1+1+0+N:N:N:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.002.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.002.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02'HISPAS:40:2:3+1+1+0+N:N:N:N:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.002.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.002.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02'HISPAS:41:3:3+1+1+0+N:N:N:N:0:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.002.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.002.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02'HICCSS:42:1:3+1+1+1'HICSES:43:1:3+1+1+1+0:90'HICSBS:44:1:3+1+1+1+N:N'HICSAS:45:1:3+1+1+1+0:90'HICSLS:46:1:3+1+1+1+J'HICCMS:47:1:3+1+1+1+500:J:J'HICMES:48:1:3+1+1+1+1:90:500:J:J'HICMBS:49:1:3+1+1+1+N:N'HICMLS:50:1:3+1+1+1'HIDSES:51:1:3+1+1+1+1:90:1:90'HIDSCS:52:1:3+1+1+1+1:90:1:90::urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02'HIDBSS:53:1:3+1+1+1+N:N'HIDSAS:54:1:3+1+1+1+1:90:1:90'HIDSLS:55:1:3+1+1+1+J'HIBSES:56:1:3+1+1+1+1:90:1:90'HIBBSS:57:1:3+1+1+1+N:N'HIBSAS:58:1:3+1+1+1+1:90:1:90'HIBSLS:59:1:3+1+1+1+J'HIDMES:60:1:3+1+1+1+1:90:1:90:500:J:J'HIDMCS:61:1:3+1+1+1+500:J:J:1:90:1:90::urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02'HIDMBS:62:1:3+1+1+1+N:N'HIDMLS:63:1:3+1+1+1'HIBMES:64:1:3+1+1+1+1:90:1:90:500:J:J'HIBMBS:65:1:3+1+1+1+N:N'HIBMLS:66:1:3+1+1+1'HICDES:67:1:3+1+1+1+1:1:360:0102030612:01020304050607080910111213141516171819202122232425262728293099'HICDBS:68:1:3+1+1+1+N'HICDNS:69:1:3+1+1+1+9:1:360:J:J:J:J:J:J:J:J:J:0102030612:01020304050607080910111213141516171819202122232425262728293099'HICDLS:70:1:3+1+1+1+0:0:N:J'HIUPA:71:4:3+9999999999+1+0'HIUPD:72:6:3+9999999999::280:10077777++9999999999+++anonym'HITAN:73:6:4+4++noref+nochallenge'HNHBS:74:1+1'
[D] > HNHBK:1:3+000000000113+300+7QHoLC57P#kJ20200311211347777%+2'HKEND:2:1+7QHoLC57P#kJ20200311211347777%'HNHBS:3:1+2'
[D] < HNHBK:1:3+000000000183+300+7QHoLC57P#kJ20200311211347777%+2+7QHoLC57P#kJ20200311211347777%:2'HIRMG:2:2+0010::Nachricht entgegengenommen.'HIRMS:3:2:2+0100::Dialog beendet.'HNHBS:4:1+2'
[D] > HNHBK:1:3+000000000406+300+0+1'HNVSK:998:3+PIN:2+998+1+1::0+1:20200311:201347+2:2:13:@8@00000000:5:1+280:10077777:<PRIVATE_>:V:0:0+0'HNVSD:999:1+@243@HNSHK:2:4+PIN:2+902+6408183+1+1+1::0+1+1:20200311:201347+1:999:1+6:10:19+280:10077777:<PRIVATE_>:S:0:0'HKIDN:3:2+280:10077777+<PRIVATE_>+0+1'HKVVB:4:3+35+0+0+<PRIVATE________________>+1.0'HKTAN:5:6+4+HKIDN'HKSYN:6:3+0'HNSHA:7:2+6408183++<PRI>''HNHBS:8:1+1'
[D] < HNHBK:1:3+000000003794+300+wO95oYe9phIy20200311211348140%+1+wO95oYe9phIy20200311211348140%:1'HNVSK:998:3+PIN:1+998+1+2::3761410428726000VV9RCMXBG5NDPO+1:20200311:211348+2:2:13:@8@        :5:1+280:10077777:<PRIVATE_>:V:0:0+0'HNVSD:999:1+@3539@HIRMG:2:2+0020::Dialoginitialisierung erfolgreich.+3060::Teilweise liegen Warnungen/Hinweise vor.'HIRMS:3:2:3+0020::Information fehlerfrei entgegengenommen.'HIRMS:4:2:4+3920::Meldung unterstützter Ein- und Zwei-Schritt-Verfahren:902+0010::Auftrag entgegengenommen. Freigabe durch TAN erforderlich.'HIRMS:5:2:5+0030::Auftrag empfangen - Sicherheitsfreigabe erforderlich'HIRMS:6:2:6+0020::Auftrag ausgeführt.'HISYN:7:4:6+3761410428726000VV9RCMXBG5NDPO'HITAN:8:6:5+4++qYvTDMUH20200311211348504#LPE#+Bitte geben Sie die photoTan ein+@3003@ 	image/png®‰PNG

```

**Comment by Philipp91** [comment]
[Hier](https://github.com/Philipp91/phpFinTS/commit/41272e33fb7e08fb56520e6a3a9dbad8475e60a1) ist die Änderung einprogrammiert, sodass es hoffentlich auch ohne vorheriges getTanModes() funktioniert. Kannst du gerne mal patchen und testen.
