### ISSUE TITLE
Unexpectedly multiple matches for Rueckmeldungscode 20 

### ISSUE THREAD

**Issue by makuser** [nemiah/phpFinTS#219]
```php
$options = new FinTsOptions();
$options->url = $cust->bank_url;
$options->bankCode = $cust->bank_code;
$options->productName = 'MEINPRODUKT';
$options->productVersion = '1.3.3.7';
$options->logger = Log::channel('single');

$credentials = Credentials::create($cust->bank_username, decrypt($cust->bank_pin));

$fints = new FinTsNew($options, $credentials);
$fints->selectTanMode(910);
$login = $fints->login();
if ($login->needsTan()) {
    handleTan($login);
}

$getSepaAccounts = GetSEPAAccounts::create();
$fints->execute($getSepaAccounts);
if ($getSepaAccounts->needsTan()) {
    handleTan($getSepaAccounts);
}
$oneAccount = $getSepaAccounts->getAccounts()[0];

$from = new DateTime('90 days ago');
$to = new DateTime();
$getStatement = GetStatementOfAccount::create($oneAccount, $from, $to);
$fints->execute($getStatement);
if ($getStatement->needsTan()) {
    handleTan($getStatement);
}

dd($getStatement->getStatement());
```

Ich habe einen part fon dem HNHBK log ausgeschnitten, da ich nicht wusste was einige der Werte bedeuten, bzw ob sie die PIN in Hash Form oder ähnlichem enthalten, etc. und bisher keine Zeit hatte das heraus zu finden.

```
[2020-01-15 18:39:06] local.DEBUG: < HNHBK:1:3+000000013187+300[...]HIRMG:3:2+3060::Bitte beachten Sie die enthaltenen Warnungen/Hinweise.'HIRMS:4:2:3+0020::Der Auftrag wurde ausgef<FC>hrt.+0020::Die gebuchten Ums<E4>tze wurden <FC>bermittelt.'HIRMS:5:2:4+3076::Starke Kundenauthentifizierung nicht notwendig.'HITAN:6:6:4+4++noref+nochallenge'HIKAZ:7:5:3+@12487@
[...]
[2020-01-15 18:39:06] local.ERROR: Unexpectedly multiple matches for Rueckmeldungscode 20 {"exception":"[object] (InvalidArgumentException(code: 0): Unexpectedly multiple matches for Rueckmeldungscode 20 at /var/customers/webs/makuser/bierkasse/vendor/nemiah/php-fints/lib/Fhp/Segment/HIRMS/FindRueckmeldungTrait.php:21)
[stacktrace]
#0 /var/customers/webs/makuser/bierkasse/vendor/nemiah/php-fints/lib/Fhp/Protocol/Message.php(198): Fhp\\Segment\\HIRMS\\HIRMSv2->findRueckmeldung(20)
#1 /var/customers/webs/makuser/bierkasse/vendor/nemiah/php-fints/lib/Fhp/BaseAction.php(213): Fhp\\Protocol\\Message->findRueckmeldung(20)
#2 /var/customers/webs/makuser/bierkasse/vendor/nemiah/php-fints/lib/Fhp/Action/GetStatementOfAccount.php(151): Fhp\\BaseAction->processResponse(Object(Fhp\\Protocol\\Message))
#3 /var/customers/webs/makuser/bierkasse/vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php(617): Fhp\\Action\\GetStatementOfAccount->processResponse(Object(Fhp\\Protocol\\Message))
#4 /var/customers/webs/makuser/bierkasse/vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php(259): Fhp\\FinTsNew->processActionResponse(Object(Fhp\\Action\\GetStatementOfAccount), Object(Fhp\\Protocol\\Message))
#5 /var/customers/webs/makuser/bierkasse/app/Console/Commands/ImportBookingEntries.php(65): Fhp\\FinTsNew->execute(Object(Fhp\\Action\\GetStatementOfAccount))
#6 [internal function]: App\\Console\\Commands\\ImportBookingEntries->handle()
#7 /var/customers/webs/makuser/bierkasse/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#8 /var/customers/webs/makuser/bierkasse/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/customers/webs/makuser/bierkasse/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#10 /var/customers/webs/makuser/bierkasse/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /var/customers/webs/makuser/bierkasse/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /var/customers/webs/makuser/bierkasse/vendor/laravel/framework/src/Illuminate/Console/Command.php(201): Illuminate\\Container\\Container->call(Array)
#13 /var/customers/webs/makuser/bierkasse/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /var/customers/webs/makuser/bierkasse/vendor/laravel/framework/src/Illuminate/Console/Command.php(188): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /var/customers/webs/makuser/bierkasse/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /var/customers/webs/makuser/bierkasse/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\ImportBookingEntries), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/customers/webs/makuser/bierkasse/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/customers/webs/makuser/bierkasse/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/customers/webs/makuser/bierkasse/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/customers/webs/makuser/bierkasse/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"} 
```

Tritt der Fehler auf, weil zwei mal `+0020::` Nachrichten von der Bank gesendet werden und das von der Lib nicht erwartet wurde?
Die Bank ist 61150020 / KSK-Esslingen / `https://banking-bw1.s-fints-pt-bw.de/fints30`.

**Comment by Philipp91** [comment]
Danke für die Info. Wurde von #213 verursacht, habe es dort gemeldet. Du kannst für den Moment einfach lokal 560d51252e34f2dfd4ccd16a890d2a02f6ea4eb2 reverten.

**Comment by makuser** [comment]
> Danke für die Info. Wurde von #213 verursacht, habe es dort gemeldet. Du kannst für den Moment einfach lokal [560d512](https://github.com/nemiah/phpFinTS/commit/560d51252e34f2dfd4ccd16a890d2a02f6ea4eb2) reverten.

Aah vielen Dank, das hatte ich gar nicht gefunden. In dem Fall ist der Fix ja relativ einfach, vielen Dank nochmals!
