### ISSUE TITLE
Fehler mit der Hypovereinsbank

### ISSUE THREAD

**Issue by thomaslanger** [nemiah/phpFinTS#358]
Seit kurzem tritt in Verbindung mit der Hypovereinsbank folgender Fehler nach Eingabe der per SMS empfangenen Pin  auf. 

Ausgabe der phpFinTS Beispielanwendung browser.php

Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 
9040 (global): Authentifizierung des Einreichers fehlerhaft - Nachricht abgelehnt. 
9800 (global): Dialoginitialisierung abgebrochen. 
9050 (global): Teilweise fehlerhaft. 
9311 (wrt seg 3): Pin/Tan-System nicht verfügbar! Bitte versuchen Sie es später noch einmal. 
Request segments: HKTAN:3:6+2++++#3815133050578776LUfaCZrWyHhtnn3zXI+N' in /Users/devel/Documents/Entwicklung/Webentwicklung/application-de/fnetcontent/library/vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170 
Stack trace: 
#0 /Users/devel/Documents/Entwicklung/Webentwicklung/application-de/fnetcontent/library/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(963): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) 
#1 /Users/devel/Documents/Entwicklung/Webentwicklung/application-de/fnetcontent/library/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(379): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) 
#2 /Users/devel/Documents/Entwicklung/Webentwicklung/application-de/fnetcontent/library/vendor/nemiah/php-fints/Samples/browser.php(60): Fhp\FinTs->submitTan(Object(Fhp\Protocol\DialogInitialization), '306983') 
#3 /Users/devel/Documents/Entwicklung/Webentwicklung/application-de/fnetcontent/library/vendor/nemiah/php-fints/Samples/browser.php(94): handleRequest(Object(stdClass), Object(Fhp\FinTs)) 
#4 {main} thrown in /Users/devel/Documents/Entwicklung/Webentwicklung/application-de/fnetcontent/library/vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 170

Bank URL: https://hbci-01.hypovereinsbank.de/bank/hbci
Bankleitzahl: 70020270
TAN-Modus: appTan-Verfahren

Der erste Schritt nach Eingabe von Benutzerkennung und Passwort/PIN, also die Abfrage der verfügbaren TAN-Modi funktioniert. SMS wird zugesendet.
Bis vor kurzem, Oktober 2021, hat es noch funktioniert. Login via Web Online-Banking und Desktopanwendung (Lexware) funktioniert.

**Comment by thomaslanger** [comment]
Es hat sich bestätigt. Ursache war ein Serverausfall bei der Hypovereinsbank
