### ISSUE TITLE
Sparda BW scheint die verfügbaren TAN Modes anders zu signalisieren

### ISSUE THREAD

**Issue by dasJ** [nemiah/phpFinTS#396]
Mit dem `browser.php` Sample bekomme ich:
```
[Fri Nov 18 11:36:33 2022] 127.0.0.1:56844 [200]: POST /browser.php - Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, null given in /tmp/comp/vendor/nemiah/php-fints/lib/Fhp/FinTs.php:845
Stack trace:
#0 /tmp/comp/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(845): array_map('intval', NULL)
#1 /tmp/comp/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(308): Fhp\FinTs->readBPD(Object(Fhp\Protocol\Message))
#2 /tmp/comp/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(832): Fhp\FinTs->execute(Object(Fhp\Protocol\DialogInitialization))
#3 /tmp/comp/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(705): Fhp\FinTs->executeWeakDialogInitialization(NULL)
#4 /tmp/comp/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(674): Fhp\FinTs->ensureSynchronized()
#5 /tmp/comp/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(532): Fhp\FinTs->ensureTanModesAvailable()
#6 /tmp/comp/Samples/browser.php(45): Fhp\FinTs->getTanModes()
#7 /tmp/comp/Samples/browser.php(94): handleRequest(Object(stdClass), Object(Fhp\FinTs))
#8 {main}
  thrown in /tmp/comp/vendor/nemiah/php-fints/lib/Fhp/FinTs.php on line 845
```

Ein naives einfügen von `if ($allowed->rueckmeldungsparameter)` führt nur dazu dass der Code später kaputt geht weil es keine TAN Methoden gibt.
Wenn mehr Informationen benötigt werden, bitte melden.

**Comment by dasJ** [comment]
Ich bekomme aber auf in der Antwort auf das erste Paket das ich sende ein Paket das u.a. einen `HITANS` Block enthält - die Werte darin sehen richtig aus:
```
(
    [parameterZweiSchrittTanEinreichung] => Fhp\Segment\TAN\ParameterZweiSchrittTanEinreichungV6 Object
        (
            [einschrittVerfahrenErlaubt] =>
            [mehrAlsEinTanPflichtigerAuftragProNachrichtErlaubt] =>
            [auftragsHashwertverfahren] => 0
            [verfahrensparameterZweiSchrittVerfahren] => Array
                (
                    [0] => Fhp\Segment\TAN\VerfahrensparameterZweiSchrittVerfahrenV6 Object
                        (
                            [sicherheitsfunktion] => 997
                            [tanProzess] => 2
                            [technischeIdentifikationTanVerfahren] => Keine TAN
…
```

**Comment by dasJ** [comment]
Wenn ich das `HIRMS` in den prettifier werden, bekomme ich:
```
HIRMS:5:2:4+3920::Zugelassene Ein- und Zwei-Schritt-Verfahren f�r den Benutzer.+0020::Informationen fehlerfrei entgegengenommen.'
Fhp\Segment\HIRMS\HIRMSv2 Object
(
    [rueckmeldung] => Array
        (
            [0] => Fhp\Segment\HIRMS\Rueckmeldung Object
                (
                    [rueckmeldungscode] => 3920
                    [bezugsdatenelement] =>
                    [rueckmeldungstext] => Zugelassene Ein- und Zwei-Schritt-Verfahren fï¿½r den Benutzer.
                    [rueckmeldungsparameter] =>
                    [referenceSegment] =>
                )

            [1] => Fhp\Segment\HIRMS\Rueckmeldung Object
                (
                    [rueckmeldungscode] => 20
                    [bezugsdatenelement] =>
                    [rueckmeldungstext] => Informationen fehlerfrei entgegengenommen.
                    [rueckmeldungsparameter] =>
                    [referenceSegment] =>
                )

        )

    [segmentkopf] => Fhp\Segment\Segmentkopf Object
        (
            [segmentkennung] => HIRMS
            [segmentnummer] => 5
            [segmentversion] => 2
            [bezugselement] => 4
        )

)
```

Kann das davon kommen dass ich keine TAN brauche für diesen Login?

**Comment by Philipp91** [comment]
Heißt das nicht einfach, dass dieser Benutzer sich nicht mit FinTS einloggen kann? Eventuell muss die Bank das erst freischalten, oder man braucht ein bestimmtes TAN-Verfahren dafür.

**Comment by dasJ** [comment]
Ich werd am Montag mal anrufen ob das extra freigeschaltet werden muss, danke für den Vorschlag :)

**Comment by dasJ** [comment]
Danke, scheinbar geht die Secure App bei FinTS nicht, man braucht ChipTAN. Danke PSD2…
