### ISSUE TITLE
Freigabeverfahren widerspricht dem Legitimationsvertrag. (MBV07390100182)

### ISSUE THREAD

**Issue by GordonInDaHouse** [nemiah/phpFinTS#421]
Hi.

I found out today that my script isn't working anymore. 
Last time I checked it was working (maybe 2-4 weeks ago)... so the error happend by itself. Something new in the bank system, is suppose.

> PHP Fatal error:  Uncaught Fhp\Protocol\ServerException: FinTS errors:
> 9050 (global): Die Nachricht enthält Fehler.
> 9930 (wrt seg 3): Freigabeverfahren widerspricht dem Legitimationsvertrag. (MBV07390100182)
> Request segments:
> HKSPA:3:2' in /var/www/html/hbci/includes/ing/vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170
> Stack trace:
> #0 /var/www/html/hbci/includes/ing/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(965): Fhp\Protocol\ServerException::detectAndThrowErrors()
> #1 /var/www/html/hbci/includes/ing/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(306): Fhp\FinTs->sendMessage()
> #2 /var/www/html/hbci/cron/spk.php(31): Fhp\FinTs->execute()
> #3 /var/www/html/hbci/cron/crons.php(193): include_once('...')
> #4 {main}
>   thrown in /var/www/html/hbci/includes/ing/vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 170
> 

It is Sparkasse with pushTan. But as I said, I wasn't touching the code for several weeks and also didn't change the Tan mode of my bank account. Another bank is still working. Just Sparkasse returns this error now. 

Has anyone the same problem or a solution for me? I need this script to be running :)

**Comment by GordonInDaHouse** [comment]
Ahh... always when the question is in Github... the answer is comming :-D

The answer to my own question is... there is a new tanMode. Mode 923 - pushTan 2.0 (of course, what else).

So, the solution is to change 921 to 923. And it is working again.
