### ISSUE TITLE
Probleme mit SEPATransfer

### ISSUE THREAD

**Issue by seem2810** [nemiah/phpFinTS#454]
Ich erhalte beim senden eines SEPA-Transfers an die Sparkasse folgende Meldung:
"This action is not awaiting decoupled confirmation" 

Leider finde ich die Quelle nicht.... 
Bei einer anderen Bank (DB) geht.

Jemand eine Idee?

**Comment by seem2810** [comment]
Ich bin etwas vorgedrungen beim Debugging:

```
[previous exception] [object] (InvalidArgumentException(code: 0): Invalid int: 6776-09-03-12.28.40.430224 at /php-fints/lib/Fhp/Syntax/Parser.php:125)
[stacktrace]
#0 php-fints/lib/Fhp/Syntax/Parser.php(429): Fhp\\Syntax\\Parser::parseDataElement()
#1 php-fints/lib/Fhp/Syntax/Parser.php(357): Fhp\\Syntax\\Parser::parseSegmentElement()
#2 php-fints/lib/Fhp/Syntax/Parser.php(466): Fhp\\Syntax\\Parser::parseSegment()
#3 [internal function]: Fhp\\Syntax\\Parser::detectAndParseSegment()
#4 php-fints/lib/Fhp/Syntax/Parser.php(483): array_map()
#5 php-fints/lib/Fhp/Protocol/Message.php(319): Fhp\\Syntax\\Parser::parseSegments()
#6 php-fints/lib/Fhp/FinTs.php(955): Fhp\\Protocol\\Message::parse()
#7 php-fints/lib/Fhp/FinTs.php(448): Fhp\\FinTs->sendMessage()
#8 Fhp\\FinTs->checkDecoupledSubmission()
```

So wirklich weiter komme ich aber noch nicht

**Comment by seem2810** [comment]
Weiterer Log... 
Jemand eine Idee?

Ich vermute, dass es am EURO-Wert in der Nachricht liegt (Komma statt Punkt?)

`[2024-09-16 09:27:24] production.DEBUG: > HNHBK:1:XXXXX:EUR:280:XXX+190,87:EUR++urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03+@3338@<?xml version="1.0" encoding="UTF-8"?>`

**Comment by seem2810** [comment]
Ich habs... 
Die Segmente waren falsch extended
